name: Publish Docker image

on:
  push:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Hub Sign-in
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t konkerlabs/konker-registry:eks-helm-deploy-v1 .
      - name: Publish Registry Images
        run: docker push konkerlabs/konker-registry:eks-helm-deploy-v1
      
